server:
  port: 9999

spring:
  datasource:
    username: root
    password: fclt
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.card.*.entity


files:
  upload:
    path: C:\Users\haozongduo\Desktop\Campus Card\photo\


multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb

